inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*
    - sorbet/**/*
    - tmp/**/*
    - vendor/**/*

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

ThreadSafety/DirChdir:
  Exclude:
    - '*.gemspec'
