name: Release

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "lib/rubocop-standard/version.rb"

jobs:
  ruby:
    uses: yettoapp/actions/.github/workflows/ruby_gem_release.yml@main
    secrets:
      rubygems_api_key: ${{ secrets.RUBYGEMS_API_BOT_KEY }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      gem_name: rubocop-standard
      version_filepath: lib/rubocop-standard/version.rb
